### ISSUE TITLE
Readme outdated?

### ISSUE THREAD

**Issue by mattse** [Dolnor/EAPD-Codec-Commander#10]
Hey Dolnor,

I've gotten working audio for my Hackintosh, but it suffers from the "no audio after wake from sleep" issue.  It's a Gigabyte H87N motherboard with realtek alc892 codec.  Your work seems like the most promising fix for this issue.

I think the readme section on ["How do I Enable It"](https://github.com/Dolnor/EAPD-Codec-Commander#how-do-i-enable-it) may be out of date or unclear.  The Default settings don't really match what is in the `info.plist` on the current master of this repository.  From the README instructions, I ended up trying this and leaving everything else the same:

```xml
<key>Default</key>
<dict>
<key>HDEF Device Location</key>
<string>1B</string>
<key>Codec Address Number</key>
<integer>2</integer>
<key>Check Infinitely</key>
<true/>
<key>Check Interval</key>
<integer>3000</integer>
<key>Custom Commands</key>
<array/>
<key>Perform Reset</key>
<false/>
<key>Perform Reset on EAPD Fail</key>
<false/>
<key>Send Delay</key>
<integer>300</integer>
<key>Sleep Nodes</key>
<true/>
<key>Update Nodes</key>
<true/>
</dict>
```

Installing the kext with this info.plist didn't fix the sleep issue.  

There's no entry for a Gigabyte board in the current master `info.plist`, nor is there an entry for Realtek ALC892 in the current master, so I was confused.  Am I doing this correctly?  Specifically, are my `HDEF Device Location` and `Codec Address Number` keys in the right location?

**Comment by Dolnor** [comment]
The readme is outdated indeed ... I will have to update it one of these weeks, which was a plan of mine anyway. But actually, looking at other profiles it's not that hard to grasp the new config. You are no longer required to specify device locations and codec numbers as this info is being pulled directly from intel hda device + the codec itself. 

It's true that there's no node for ALC892, therefore you have to create one yourself. No special commands needed, but reset is mandatory (same on my H87-HD3 with 892). So you are expected to come up with something looking awfully similar to below code snippet:

				<key>Realtek ALC892</key>
				<dict>
					<key>Check Infinitely</key>
					<false/>
					<key>Codec Id</key>
					<array>
						<string>0x10ec0892</string>
					</array>
					<key>Perform Reset</key>
					<true/>
					<key>Send Delay</key>
					<integer>100</integer>
					<key>Sleep Nodes</key>
					<false/>
				</dict>

**Comment by mattse** [comment]
Thanks for the quick reply.  I tried putting exactly your config into my `Info.plist`, but unfortunately my sound still fails after sleep.  My current hackaround is to just turn off auto system sleep and never go into that mode.

**Comment by icezar** [comment]
I used the following syntax for solving the "no sound after sleep" issue on an AsRock Extreme4 ALC898 codec:

`<key>Realtek ALC898</key>`
`<dict>`
`<key>Check Infinitely</key>`
`<false/>`
`<key>Codec Id</key>`
`<array>`
`<string>0x10ec0898</string>`
`</array>`
`<key>Perform Reset</key>`
`<true/>`
`<key>Send Delay</key>`
`<integer>100</integer>`
`<key>Sleep Nodes</key>`
`<false/>`
`</dict>`

I pinned it between the other ALC definitions. It would be great if more chips would be added to the default configuration.

I also used darkwake=8 as a boot flag in my clover bootloader. I believe Chameleon also accepts this flag. This flag ensures that certain components of the PC are ON while the PC is sleeping.

For details on darkwake, check the following 2 links:
http://mactips.dwhoard.com/mactips/system/wake-on-demand/20130516-email-wod-chrisb
http://www.google.com/patents/US7996694

**Comment by alexschomb** [comment]
I can confirm the issues with ALC892 that @mattse has. I added the suggested definition of @Dolnor directly below the default ALC definitions. After waking up from sleep audio is not working, no sound. I've set darkwave=8 in Clover, too.

**Comment by Dolnor** [comment]
I had darkwake set to 6 for ages on my HD87-HD3 plus the code snippet I have provided - works a treat.

What may have be an obvious problem here for both of you is that CodecCommander detects EAPD capable nodes, even though there are no EAPD's physically on the chip .. which causes the chip to stall when these nodes are sent the verbs to update said EAPDs.

Try setting Update Nodes to No (</false> ) for AL892 configuration. 

Also, don't push the codec with sound right at wake, or it will stall for some time to properly initialize. As in, if you put your computer to sleep with a youtube video playing in background chances are it won't resume with working audio right away.

**Comment by alexschomb** [comment]
Thanks for your fast response. I tried setting Update Nodes to NO, but it doesn't help the sound. At the same time my USB devices won't be recognized anymore and only come back again after several minutes. At least that means that CodecCommander.kext is working and recognizes the right ALC892 definition.

I also tried setting darkwave=10, but that didn't help either. I suppose that you had a typo, because AFAIK there is no darkwave=6.

I also did some test and waited several minutes (Well, I had to because my mice and keyboard wouldn't be recognized.) before playing any sound. Even after 10 minutes there is no sound output at all - with either combination of settings (Update Nodes, darkwave).

**Comment by icezar** [comment]
I would maybe look somewhere else like your DSDT or the patch type you are using. I would advise to open a thread on one of the Hackintosh communities like insanelymac or tonymacx86.

**Comment by alexschomb** [comment]
Actually, this is how I ended up here. Dolnors EAPD solution was recommended by several people for the combination of ALC892 and cloverALC.
http://www.tonymacx86.com/audio/152953-solved-no-sound-after-sleep-alc892-yosemite-clover-help-fix.html#post953668
http://www.tonymacx86.com/audio/151504-no-audio-after-sleep-wake-realtek-alc-applehda-fixes.html

The old settings should be working, but the syntax changed (as pointed out by @mattse) and I was trying to get it working with the new version. What would be the recommended commit to make it work with the old syntax?

**Comment by Dolnor** [comment]
You can try:
		git clone https://github.com/Dolnor/EAPD-Codec-Commander
		git reset --hard 5b660f07814f45c2a3cacd8548c3b8d70ef7d9cb
Compiling and setting up a profile for this one should work for sure, as this is what works for me.

I've tried using binary compiled from the latest merges and there indeed seems to be a problem of resetting the codec related to changes implemented for mapping direct Mem IO. Since this was @the-darkvoid and @RehabMan commits, I can't iron the root cause. Submitted an Issue to @RehabMan's fork, he may be able to localize the problem faster I think.

**Comment by alexschomb** [comment]
Thanks! That did the trick. Works like a charm :+1: 

(Also thanks for the explanations concerning darkwave. I should have a more detailed look in the documentation.)

**Comment by Dolnor** [comment]
Readme updated to reflect changes in the code base.
