### ISSUE TITLE
ALC1150 no audio after Windows restart

### ISSUE THREAD

**Issue by Alisamix** [Dolnor/EAPD-Codec-Commander#11]
Hi!

I read the issue https://github.com/Dolnor/EAPD-Codec-Commander/issues/9 to fix my problem.

I do have sound after sleep, which is already great! But after I added the custom commands from that issue to my kext, nothing really changed - How should I proceed to fix my sound?

**Comment by Dolnor** [comment]
Custom commands are stored as data now, not Integer. [More on Custom Command configuration] (https://github.com/Dolnor/EAPD-Codec-Commander#custom-commands--commander-client)

**Comment by Alisamix** [comment]
What does this mean in my specific case? Should I convert it to Base64?

**Comment by Alisamix** [comment]
Nvm, I forgot the Profile. Works perfect, thanks!

**Comment by nixcamic** [comment]
Alisamix would you be able to post your info.plist in full? I'm still having trouble getting mine to work.

**Comment by Dolnor** [comment]
Add under Codec Profile sections:

                <key>10ec_0900</key>
                <string>Realtek ALC1150</string>
                <key>Realtek ALC1150</key>
                <dict>
                    <key>Custom Commands</key>
                    <array>
                        <dict>
                            <key>Command</key>
                            <data>
                            AgUABw==
                            </data>
                            <key>Comment</key>
                            <string>SET_COEF_INDEX</string>
                            <key>On Init</key>
                            <true/>
                            <key>On Sleep</key>
                            <true/>
                            <key>On Wake</key>
                            <true/>
                        </dict>
                        <dict>
                            <key>Command</key>
                            <data>
                            AgR8sA==
                            </data>
                            <key>Comment</key>
                            <string>SET_PROC_COEF</string>
                            <key>On Init</key>
                            <true/>
                            <key>On Sleep</key>
                            <false/>
                            <key>On Wake</key>
                            <true/>
                        </dict>
                    </array>
                    <key>Update Nodes</key>
                    <false/>
                    <key>Sleep Nodes</key>
                    <false/>
                    <key>Send Delay</key>
                    <integer>100</integer>
                </dict>

**Comment by nixcamic** [comment]
Heh, I'd accidentally put it under the VoodooHDA Codec Profile. Whoops, thats what I get for just hitting Apple + F then pasting... Everything's golden now, thanks a ton!
