### ISSUE TITLE
Front audio panel broken after sleep

### ISSUE THREAD

**Issue by korzhyk** [Dolnor/EAPD-Codec-Commander#13]
On fresh OSX startup I can use my headphones through front panel audio ports, but after sleep don't recognize my headphones and as a fact speakers continue play sounds like no where connected to front panel audio port.

**Comment by Dolnor** [comment]
You have codec commander client, custom commands and other codec profiles to rely upon, which have similar issues. Determine the headphone node and try setting unsolicited for it. Not a code issue here, as such it's being closed.

**Comment by korzhyk** [comment]
You write about a CodecCommanderClient executable file. But I don't know how to operate this program, is there a manual for this cli program or HOWTO solve this problem?

**Comment by Dolnor** [comment]
hda-verb for CodecCommander (based on alsa-tools hda-verb)
		usage: hda-verb [option] nid verb param
		   -l      List known verbs and parameters
		   -L      List known verbs and parameters (one per line)
