### ISSUE TITLE
A crackling noise when sound plays occasionally like notification sounds, email dings etc

### ISSUE THREAD

**Issue by tigersoul925** [Dolnor/EAPD-Codec-Commander#16]
I have NO idea if this issue is related to codec-commander or audio_RealtekALC. I'll post this in both places to see where it ends up being.

When no sound has been playing for a little while, sometimes a crackling sound is heard in the beginning of the sound played. Primarily happens with email dings, facebook sounds etc. It sounds as if a speaker is flipped on for the sound. Sounds occuring right after is not affected. It only seems to happen for sounds when things have been silent for a while.

**Comment by Dolnor** [comment]
Not something I can help you with as this happens on Apple hardware, except Mac Pros where codec doesn't enter D3cold to conserve power. This popping/crackling happens on iMac, Macbooks and Minis. It's a part of Apple's power saving policy intended for audio codecs .. AFAIK the only workaround for this is using antipop, to periodically feed codec a silent phrase of space via _say_ command.

Also, you didn't even bother mentioning what hardware this problem surfaces on, which is the first rule of ticketing.

**Comment by tigersoul925** [comment]
Sorry. This was more of a "check-up" level of report. I wasn't at all sure whether it was an issue at all or not, suspecting something like you just suggested regarding power policy. I've had genuine macs for a while but never noticed any popping/crackling sound like this before. Maybe I haven't been paying attention. I'll look into the antipop thing and see if that helps. If it does, that's probably it. Thanks for replying! This is probably good to keep available for others thinking about the same issue.

Hardware is Gigabyte Z97MX-Gaming 5, i7-4790K.

EDIT: After looking closer I hear a faint click after 37 secs of inactivity sound-wise. When the next sound comes on there will be a pop in the beginning of the sound. You were right, this is my issue. I can also add for those coming this way: antipop works for most, many find it works using mac pro 3,1 as system profile as well, but this is probably not appropriate for most modern systems with nvidia cards afaik.

Thanks for your help Dolnor!
