### ISSUE TITLE
Codec Commander not loading?

### ISSUE THREAD

**Issue by Simanias** [Dolnor/EAPD-Codec-Commander#6]
Hi Dolnor,

First of all thanks for your hard work.
I'm running on a Gigabyte Z97X-UD7 TH
I've compiled Codec Commander and changed the info.plist to match my audio.
![screen shot 2015-01-07 at 20 58 54](https://cloud.githubusercontent.com/assets/4976061/5652361/0dd32770-96b0-11e4-862b-5686976eb2fe.png)

![screen shot 2015-01-07 at 20 56 54](https://cloud.githubusercontent.com/assets/4976061/5652349/e27a22a4-96af-11e4-836e-b391fe265afd.png)

Somehow it doesn't seem to load properly if I look at the console, any thoughts?

07/01/15 20:51:09,000 kernel[0]: CodecCommander: Version 2.2.1 starting.
07/01/15 20:51:09,000 kernel[0]: CodecCommander::IntelHDA
07/01/15 20:51:09,000 kernel[0]: ....Codec Version:	255.255
07/01/15 20:51:10,000 kernel[0]: Sound assertion - Command/Response TIMED OUT and ( kRequestStateMatch == fCodecRequest->state = 2 ), fCodecRequest->command->codec: 0xffffff804ee18a00, fCodecRequest->command->verb: 0xF0000, fPoweredDown: 0
07/01/15 20:51:10,000 kernel[0]: Sound assertion in IOHDACodecDevice at line 145
07/01/15 20:51:10,000 kernel[0]: Sound assertion in IOHDACodecDevice at line 551
07/01/15 20:51:11,000 kernel[0]: Sound assertion - Command/Response TIMED OUT and ( kRequestStateMatch == fCodecRequest->state = 2 ), fCodecRequest->command->codec: 0xffffff804ee18a00, fCodecRequest->command->verb: 0xF0000, fPoweredDown: 0
07/01/15 20:51:11,000 kernel[0]: Sound assertion in IOHDACodecDevice at line 145
07/01/15 20:51:11,000 kernel[0]: Sound assertion in IOHDACodecDevice at line 551

Regards,
Simania

**Comment by Dolnor** [comment]
Hey, sorry for getting at you so late, Samania.
Try removing the Custom Commands section from the Default config. But it seems like it's your AppleHDA that isn't not loading, not the CodecCommander. All these sound assertions are coming from AppleHDA.

**Comment by Simanias** [comment]
Dolnor thanks for your reply and effort, but I have switched to EAPD fix kexy from emlydinesh. That kext worked straight away. Thanks.
