### ISSUE TITLE
Sound stopping during Video

### ISSUE THREAD

**Issue by alexanderreynolds** [Dolnor/EAPD-Codec-Commander#7]
Hi i have a big problem with my AppleHDA. Sometimes the AppleHDA powers the EAPD just out of the box down and i have no sound coming from the Headphones/Speakers. Is there a way to enable Codec Commander to check every ~3 minutes if the HDA codec lost power?
Thanks

**Comment by Dolnor** [comment]
It checks this every X milliseconds that you specify in config for the Check Interval property, provided Check Infinitely is enabled. When power is restored to the codec then an immediate verb is sent to the codec to enable the EAPD.

**Comment by alexanderreynolds** [comment]
I have both, "Check Infinitely" enabled and "check Interval" set for 100:
	<key>Check Infinitely</key>
	<true/>
	<key>Check Interval</key>
	<integer>100</integer>

**Comment by Dolnor** [comment]
You do realize it's 100 ms? Can you picture the driver parsing 4 things at once in a course of 100ms ?
Set it to at least 1000.

**Comment by alexanderreynolds** [comment]
Ok i changed it to 1000 but it's still not working...

**Comment by Dolnor** [comment]
Would you care to compile a debug build and provide some for of logging ?
Saying "it doesn't work" is not enough for things like this.

**Comment by alexanderreynolds** [comment]
Yeah sure, sorry haven't thought about that :)

Here is the log after going to sleep mode and waking it up:

13.02.15 20:56:48,000 kernel[0]: CodecCommander: cc - power state transition from 2 to 0 recorded
13.02.15 20:56:48,000 kernel[0]: CodecCommander: HDA codec lost power
13.02.15 20:56:48,000 kernel[0]: CodecCommander: cc: --> custom command 0x000f0000
13.02.15 20:56:51,000 kernel[0]: CodecCommander: cc: --> asleep
13.02.15 20:56:52,000 kernel[0]: CodecCommander: cc: --> custom command 0x000f0000
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> awake
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> resetting codec
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> hda codec power restored
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> custom command 0x000f0000
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> workloop started
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc - power state transition from 0 to 2 recorded

And after booting the system:

13.02.15 20:56:48,000 kernel[0]: CodecCommander: cc - power state transition from 2 to 0 recorded
13.02.15 20:56:48,000 kernel[0]: CodecCommander: HDA codec lost power
13.02.15 20:56:48,000 kernel[0]: CodecCommander: cc: --> custom command 0x000f0000
13.02.15 20:56:51,000 kernel[0]: CodecCommander: cc: --> asleep
13.02.15 20:56:52,000 kernel[0]: CodecCommander: cc: --> custom command 0x000f0000
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> awake
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> resetting codec
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> hda codec power restored
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> custom command 0x000f0000
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc: --> workloop started
13.02.15 20:57:33,000 kernel[0]: CodecCommander: cc - power state transition from 0 to 2 recorded
13.02.15 18:07:39,000 kernel[0]: CodecCommander: IOAudioPowerState unknown
[...] (about 40 times)
13.02.15 18:07:39,000 kernel[0]: CodecCommander: IOAudioPowerState unknown
13.02.15 18:07:40,000 kernel[0]: CodecCommander: cc - power state transition from 0 to 2 recorded

Whats interesting that after i changed the interval to 1000 the sound stopped working much quicker that with 100 so i changed it back again xD

Thanks for your help

**Comment by Dolnor** [comment]
Try removing this custom command (or set all the toggles to NO when to run it) from the Detault configuration. maybe your codec doesn't play nicely with it.

**Comment by alexanderreynolds** [comment]
So I downloaded the entire xcodeproject and build it by myself and installed without changing any settings, but still i get the Log: 05.04.15 15:55:18,000 kernel[0]: CodecCommander: cc: --> hda codec power restored - but the codec is offline and i can't hear anything... Please help
