### ISSUE TITLE
Audio lost after sleep 10.10.2 (14C1514)

### ISSUE THREAD

**Issue by am** [Dolnor/EAPD-Codec-Commander#8]
This was working with 10.10.2. After the OS security updates the problem returned. Is this something that should be fixed in this project? Are you affected by this problem also, or could it be a

**Comment by Dolnor** [comment]
It's just you, I think. I'm on 10.10.3 and went through a couple of betas already .. not a single hiccup. I can't imagine how a security update could have affected your sound, it's most likely something on your end. Try rebuilding kernel cache for starters.
